# Use an official Nginx runtime as a parent image
FROM nginx:alpine

# Copy the custom nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the static assets from the frontend directory
COPY ./frontend /usr/share/nginx/html
